### PR TITLE
For tab and multibyte characters.

### PR DESCRIPTION
**Pull request by machakann**
Hi I have learned about vital-coaster and this fixes the problem #8 probably. Could you check it if there is any problem?

### CODE REVIEW

**Comment by Asdas91** [comment]
Cool, your commit fixes the problem for me and that is great because at work we are forced to use tabs for indentation.

**Comment by machakann** [comment]
@haya14busa I don't want to disturb you but a few people might be happy if you took care of this PR. Thank you for your consideration.

**Comment by haya14busa** [comment]
I'm really sorry for the late response :bowing_man:  It looks good to me :+1:

Using real or virtual col is sometimes difficult and breaks unexpected cases, but since vital-coast uses `\%v`,  indeed `virtcol()` is right in this case.

**Comment by machakann** [comment]
Thank you!

**Pull request merged**
